import NSBarrier.NSTorusShellActual
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.Tactic

open NSTorusShellActual

namespace NSTorusShellFinite

/-- The shell basis set is finite because it is the image of a finite set of modes. -/
theorem shellBasisSet_finite (M : Finset Mode) :
    (shellBasisSet M).Finite := by
  classical
  simpa [shellBasisSet] using M.finite_toSet.image basisVec

/-- The shell subspace generated by finitely many Fourier modes is finite-dimensional. -/
instance shellSubspace_finiteDimensional (M : Finset Mode) :
    FiniteDimensional ℂ ↥(shellSubspace M) := by
  classical
  simpa [shellSubspace] using
    (FiniteDimensional.span_of_finite ℂ (shellBasisSet_finite M))

/-- Finite-dimensional subspaces over `ℂ` are complete. -/
noncomputable instance shellSubspace_complete (M : Finset Mode) :
    CompleteSpace ↥(shellSubspace M) := by
  letI : FiniteDimensional ℂ ↥(shellSubspace M) :=
    shellSubspace_finiteDimensional M
  letI : IsUniformAddGroup ↥(shellSubspace M) :=
    (shellSubspace M).toAddSubgroup.isUniformAddGroup
  exact FiniteDimensional.complete ℂ ↥(shellSubspace M)

/-- Hence each shell subspace admits an orthogonal projection. -/
noncomputable instance shellSubspace_hasOrthogonalProjection (M : Finset Mode) :
    (shellSubspace M).HasOrthogonalProjection := by
  letI : CompleteSpace ↥(shellSubspace M) := shellSubspace_complete M
  infer_instance

/-- The actual shell projector, now with no extra assumption argument. -/
noncomputable def shellProj' (M : Finset Mode) : L2T3 →L[ℂ] L2T3 :=
  shellProj M

/-- Contraction of the unconditional actual shell projector. -/
theorem shellProj'_apply_norm_le (M : Finset Mode) (f : L2T3) :
    ‖shellProj' M f‖ ≤ ‖f‖ := by
  simpa [shellProj'] using shellProj_apply_norm_le M f

/-- The actual family of shell projectors, now with no extra assumption argument. -/
noncomputable def shellProjFamily' {K_max : ℕ} (modes : ModeFamily K_max) :
    Fin K_max → (L2T3 →L[ℂ] L2T3) :=
  shellProjFamily modes

/-- Contraction of each actual shell projector in the family. -/
theorem shellProjFamily'_contraction {K_max : ℕ} (modes : ModeFamily K_max)
    (k : Fin K_max) (f : L2T3) :
    ‖shellProjFamily' modes k f‖ ≤ ‖f‖ := by
  simpa [shellProjFamily'] using shellProjFamily_contraction modes k f

#check @shellBasisSet_finite
#check @shellSubspace_finiteDimensional
#check @shellSubspace_complete
#check @shellSubspace_hasOrthogonalProjection
#check @shellProj'
#check @shellProj'_apply_norm_le
#check @shellProjFamily'
#check @shellProjFamily'_contraction

end NSTorusShellFinite
