name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"
          ~/.elan/bin/elan default stable

      - name: Build (Lean)
        working-directory: lean4
        run: |
          lake update
          lake build

      - name: Build docs (doc-gen)
        working-directory: lean4
        run: |
          lake exe docs
